apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: ai
spec:
  config: '{
    "cniVersion": "0.3.0",
    "plugins": [
      {
        "type": "macvlan",
        "capabilities": { "ips": true },
        "master": "enp0",
        "mode": "bridge",
        "ipam": {
          "type": "static"
        }
      }]
    }'
