apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
          k8s.v1.cni.cncf.io/networks: '[ { "name": "macvlan-conf","ips":[ "192.168.100.101/24" ] } ]'
spec:
        #  nodeSelector:
        #    kubernetes.io/hostname: node1
  containers:
    - name: samplepod
      command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
      image: ubuntu
