---
- name: restart docker
  command: /bin/true
  notify:
    - Docker | reload systemd
    - Docker | reload docker
    - Docker | wait for docker

- name: Docker | reload systemd
  systemd:
    daemon_reload: true

- name: Docker | reload docker
  service:
    name: docker
    state: restarted

# 验证docker是否正常启动了
- name: Docker | wait for docker
  command: "{{ docker_bin_dir }}/docker images"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0
