---
docker_kernel_min_version: '0'

# https://docs.docker.com/install/linux/docker-ce/fedora/
# https://download.docker.com/linux/fedora/<fedora-version>/x86_64/stable/Packages/

docker_versioned_pkg:
  'latest': docker-ce
  '18.03': docker-ce-18.03.1.ce-3.fc{{ ansible_distribution_major_version }}
  '18.06': docker-ce-18.06.2.ce-3.fc{{ ansible_distribution_major_version }}
  '18.09': docker-ce-18.09.7-3.fc{{ ansible_distribution_major_version }}
  '19.03': docker-ce-19.03.8-3.fc{{ ansible_distribution_major_version }}

# Fedora 30/31 don't provide packages for docker 18.0x ...
docker_version: "19.03"

docker_package_info:
  pkg_mgr: dnf
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
