---

- name: install virtualenv and set setuptools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "virtualenv"
    - "python-setuptools"
  when: ansible_distribution == 'Ubuntu'

- name: create location for K8s4ML files
  file:
    path: "{{ deepops_dir }}"
    state: directory

- name: install openshift python client for k8s_raw module
  pip:
    name: openshift
    virtualenv: "{{ deepops_venv }}"
  when: ansible_distribution == 'Ubuntu'
  environment: "{{proxy_env if proxy_env is defined else {}}}"
