---

- hosts: localhost
  gather_facts: false
  become: no
  tasks:
    - name: "Check ansible version >= 2.7.8"
      assert:
        msg: "Ansible must be v2.7.8 or higher"
        that: # ansible_version is kind of special variables in ansible
              # Dictionary/map that contains information about the current running version of ansible, it has the following keys: full, major, minor, revision and string.
          - ansible_version.string is version("2.7.8", ">=")
      tags:
        - check
  vars: # ansible_connection is kind of special variables in ansible
        # The connection plugin actually used for the task on the target host
    ansible_connection: local

- hosts: k8s-cluster:etcd # 这里表示的target是k8s-cluster和etcd组(不是&和!)
                          # 因为这里我的etcd是一个节点并且是在master上，所以这里的效果和hosts: k8s-cluster是一样的
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}" # 有任务错误时，立即停止
  gather_facts: false
  roles:
    - { role: kubespray-defaults} # 什么也每执行基本，因为skip_downloads是true
    - { role: bootstrap-os, tags: bootstrap-os}

#
#到目前为之，安装了python, 按照inventory_name更改了各个主机的名字
#剩下的什么也每做
#

- hosts: k8s-cluster:etcd
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults} # 用来使用一些其中的变量 skip_downlads is true
    - { role: kubernetes/preinstall, tags: preinstall }
    - { role: "container-engine", tags: "container-engine", when: deploy_container_engine|default(true) }
    - { role: download, tags: download, when: "not skip_downloads" }
      # 这里的download是执行的, 因为kubespray-defaults中的skip_downloads true是在执行kubespray-defaults时， meta中强打进去的变量, 出了kubespray-defaults就失效了. 但是其他的vars是可以共享的（除了那些特殊打入的变量不能外部rols共享）

