---

# Kuberbetes Cluster playbook

# Install python required for Ansible
- include: bootstrap-python.yml
  tags:
    - bootstrap

# Set up passwdless sudo and SSH Keys if needed
- include: bootstrap-ssh.yml
  tags:
    - bootstrap
- include: bootstrap-sudo.yml
  tags:
    - bootstrap

# Configure Chrony (NTP) sync
- include: chrony-client.yml

# Install the OpenShift API libraries required by the GPU plugin
# openshift是基于容器计数搭建的一个云平台。这里的容器技术即包括Docker和Kunbernetes
- include: bootstrap-openshift.yml
  tags:
    - bootstrap

# Install 'sshpass' program for: https://github.com/ansible/ansible/issues/56629
- hosts: all
  gather_facts: true
  tasks:
    - name: install sshpass
      package: # Installs, upgrade and removes packages using the underlying OS package manager.
               # https://docs.ansible.com/ansible/latest/modules/package_module.html#package-module
        name: sshpass
        state: present
  tags:
    - bootstrap

# Install Kubernetes
# for configuration, see: config/group_vars/k8s-cluster.yml
- include: ../kubespray/cluster.yml
  tags:
    - k8s

# Disable swap (required for k8s), kubespray method doesn't quite cut it
- hosts: k8s-cluster
  become: true
  tasks:
    - name: remove swap from fstab
      lineinfile: path=/etc/fstab regexp='swap' state=absent
    - name: disable swap
      command: swapoff -a
  tags:
    - swap

# Install NVIDIA driver on GPU servers
- include: nvidia-driver.yml hostlist=kube-node
  tags:
    - nvidia
  when: deepops_gpu_operator_enabled | default('false') | bool == false

# Install NVIDIA container runtime on GPU servers
- include: nvidia-docker.yml hostlist=kube-node
  tags:
    - nvidia
  when: deepops_gpu_operator_enabled | default('false') | bool == false

# Install k8s GPU device plugin
- include: k8s-gpu-plugin.yml
  tags:
    - nvidia
  when: deepops_gpu_operator_enabled | default('false') | bool == false


# The GPU-operator is good, but for some reason, my nfd(node feature discovery)# always cannot find out GPU lable on node. So, I decide to use traditional way
# Install NVIDIA GPU Operator
- include: nvidia-gpu-operator.yml
  tags:
    - nvidia
  when: deepops_gpu_operator_enabled | default('false') | bool == true
