---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
    - name: install custom facts module
      include_role:
        name: facts

    - name: remove docker overrides from DGX OS
      file:
        path: /etc/systemd/system/docker.service.d/docker-override.conf
        state: absent

    - name: install nvidia-docker
      include_role:
        name: nvidia.nvidia_docker
      when:
        - ansible_local['gpus']['count'] and (ansible_distribution == "Ubuntu" or ansible_os_family == "RedHat")
  environment: "{{proxy_env if proxy_env is defined else {}}}"
